### ISSUE TITLE
400 errors produce cryptic exception messages

### ISSUE THREAD

**Issue by stickfigure** [paypal/PayPal-Java-SDK#109]
toString() on an InputStream does not provide the desired behavior :-)

```
Caused by: com.paypal.base.rest.PayPalRESTException: Response Code : 400 with response : java.io.ByteArrayInputStream@27cded0c
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:416)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:265)
	at com.paypal.api.payments.Payment.execute(Payment.java:402)
	at com.gearlaunch.hub.pay.PayPaler.execute(PayPaler.java:113)
	... 54 more
Caused by: com.paypal.base.exception.ClientActionRequiredException: Response Code : 400 with response : java.io.ByteArrayInputStream@27cded0c
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:130)
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:65)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:407)
	... 57 more
```

**Comment by juwlee** [comment]
@stickfigure can you share your request body so I can reproduce the issue? It seems the root exception is thrown from [here](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/HttpConnection.java#L129), which means the response code is not 2xx. 400 indicates some client-side error, and I will add the details to the error message.

**Comment by stickfigure** [comment]
Well, this issue is just about the fact that you aren't printing the contents of the buffer. While nice, I don't expect you to try to figure the root cause.

I don't think this is going to help you much, but here's the request:
https://api.sandbox.paypal.com/v1/payments/payment/PAY-8JF91702U9637574WKWGCODY/execute
Body: {}

The actual response: 
{"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"7b52903f61be5"}

**Comment by stickfigure** [comment]
I guess the question remains - how do I go about debugging UNKNOWN_ERROR? I apologize if this isn't the right forum for this question... but what is?

**Comment by juwlee** [comment]
Please open a new issue for 5xx error with `debug_id`. As the error is thrown on server-side, it needs to be investigated on paypal's end. I will have a look at the `debug_id` that you posted and update when I have something to share.

**Comment by juwlee** [comment]
@stickfigure actually, `[PayPalResource.LASTRESPONSE](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/rest/PayPalResource.java#L55)` should have the error details. You could access it from your `Payment` instance as it is a subclass of `PayPalResource` class. I will update the error message to make it less cryptic without the hashcode.

**Comment by juwlee** [comment]
@stickfigure same as #111 , can you please try out the fix on `v1.2.6` branch?

**Comment by juwlee** [comment]
Closing due to inactivity. Please try the latest version and re-open if problem persists.

**Comment by ackdev** [comment]
Hi, PayPalResource.LASTRESPONSE is still null even after receiving below message:

 Response Code : 401 see PayPalResource.LASTRESPONSE for details. (BillingBean.java:213)
com.paypal.base.rest.PayPalRESTException: Response Code : 401 see PayPalResource.LASTRESPONSE for details.
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:416)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:265)
	at com.paypal.api.payments.Payment.create(Payment.java:307)

**Comment by stickfigure** [comment]
I also get `null` from PayPalResource.getLastResponse() even when I get `400 see PayPalResource.LASTRESPONSE for details.`

**Comment by stickfigure** [comment]
The reason for this is bug #118

**Comment by ackdev** [comment]
Thanks, I'm using 1.2.6 as well, same issue.  Guess I'll patch locally for now

**Comment by togaurav** [comment]
**Please find the detail that I collected from paypal sandbox console:**
## MetaData
{
	"url": "/v1/payments/payment",
	"create_time": "2015-10-01T08:21:14Z",
	"additional_properties": {},
	"account_number": "2112703502376077204",
	"client_id": "AZe3YVV6eONU4QqC-YJw1elPwHuUGwMoUapg_H7KPDWU5IUboDyahOCDoOgo04y9RuBTK6m_TzDzngn8",
	"id": "560cecfb36b75d4776921a9f"
}

## Request:
{
	"body": {
		"intent": "sale",
		"payer": {
			"payment_method": "credit_card",
			"funding_instruments": [
				{
					"credit_card": {
						"first_name": "John Doe",
						"expire_month": 4,
						"number": "xxxxxxxxxxxx5105",
						"cvv2": "***",
						"expire_year": 2018,
						"type": "visa"
					}
				}
			]
		},
		"transactions": [
			{
				"amount": {
					"currency": "USD",
					"total": "21.29"
				}
			}
		]
	},
	"header": {
		"x-pp-ads-performed": "false",
		"content-length": "460",
		"paypal-request-id": "2dc480f7-66e8-4bf2-87e0-ee93db9526a3",
		"x-pp-silover": "name%3DSANDBOX3.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D4209773654",
		"connection": "keep-alive",
		"accept": "text/html, image/gif, image/jpeg, *; q\\u003d.2, */*; q\\u003d.2",
		"client-auth": "No cert",
		"host": "api.sandbox.paypal.com",
		"user-agent": "PayPalSDK/PayPal-Java-SDK 1.2.8 (lang\\u003dJava;v\\u003d1.7.0_45;bit\\u003d64;os\\u003dWindows_8 6.2)",
		"authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx2dZ8",
		"x-pp-corrid": "9ebc4647bd344",
		"pp_remote_addr": "106.51.225.141",
		"content-type": "application/json",
		"x-pp-slingshot-targetapp": "platformapiserv"
	},
	"additional_properties": {},
	"method": "POST"
}

## Response:
{
	"status": 400,
	"duration_time": 735,
	"body": {
		"message": "An unknown error has occurred",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR",
		"name": "UNKNOWN_ERROR",
		"debug_id": "9ebc4647bd344"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "185",
		"Content-Language": "*",
		"CORRELATION-ID": "9ebc4647bd344",
		"Date": "Thu, 01 Oct 2015 08:21:15 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "9ebc4647bd344",
		"PROXY_SERVER_INFO": "host\\u003dslcsbplatformapiserv3001.slc.paypal.com;threadId\\u003d423",
		"Content-Type": "application/json"
	}
}
