### ISSUE TITLE
NullPointerException on Google App Engine

### ISSUE THREAD

**Issue by stickfigure** [paypal/PayPal-Java-SDK#111]
When using the SDK on GAE (in production), I get this exception. It doesn't happen when running in the local dev instance.

```
    W 13:23:32.675 /api/campaigns/ahhzfmdlYXJsYXVuY2gtaHViLXNhbmRib3hyEQsSCENhbXBhaWduGIGD-QEM/orders/paypal
      org.jboss.resteasy.spi.UnhandledException: java.lang.ExceptionInInitializerError
      	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:76)
      	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:212)
      	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:149)
      	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:372)
      	at org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:217)
      	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:224)
      	at org.jboss.resteasy.plugins.server.servlet.FilterDispatcher.doFilter(FilterDispatcher.java:62)
      	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
      	at com.gearlaunch.hub.util.BasicAuthFilter.doFilter(BasicAuthFilter.java:100)
      	at com.gearlaunch.hub.util.PrivateAuthFilter.doFilter(PrivateAuthFilter.java:33)
      	at com.gearlaunch.hub.util.AbstractFilter.doFilter(AbstractFilter.java:48)
      	at com.voodoodyne.rollbar.AppengineRollbarFilter$TrappingFilterChain.doFilter(AppengineRollbarFilter.java:43)
      	at com.tapstream.rollbar.RollbarFilter.doFilter(RollbarFilter.java:37)
      	at com.voodoodyne.rollbar.AppengineRollbarFilter.doFilter(AppengineRollbarFilter.java:58)
      	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
      	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
      	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
      	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
      	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
      	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
      	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
      	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
      	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
      	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
      	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
      	at org.mortbay.jetty.Server.handle(Server.java:326)
      	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
      	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
      	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
      	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
      	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
      	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:482)
      	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
      	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
      	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
      	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
      	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:234)
      	at java.lang.Thread.run(Thread.java:745)
      Caused by: java.lang.ExceptionInInitializerError
      	at com.paypal.base.DefaultHttpConnection.<init>(DefaultHttpConnection.java:35)
      	at com.paypal.base.ConnectionManager.getConnection(ConnectionManager.java:37)
      	at com.paypal.base.rest.OAuthTokenCredential.generateOAuthToken(OAuthTokenCredential.java:194)
      	at com.paypal.base.rest.OAuthTokenCredential.generateAccessToken(OAuthTokenCredential.java:165)
      	at com.paypal.base.rest.OAuthTokenCredential.getAccessToken(OAuthTokenCredential.java:133)
      	at com.gearlaunch.hub.pay.PayPaler.getApiContext(PayPaler.java:105)
      	at com.gearlaunch.hub.pay.PayPaler.createPayment(PayPaler.java:47)
      	at com.gearlaunch.hub.res.CampaignsOrders.createPayPal(CampaignsOrders.java:92)
      	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      	at java.lang.reflect.Method.invoke(Method.java:45)
      	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
      	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
      	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
      	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
      	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
      	at org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:217)
      	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:224)
      	at org.jboss.resteasy.plugins.server.servlet.FilterDispatcher.doFilter(FilterDispatcher.java:62)
      	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
      	at com.gearlaunch.hub.util.BasicAuthFilter.doFilter(BasicAuthFilter.java:100)
      	at com.gearlaunch.hub.util.PrivateAuthFilter.doFilter(PrivateAuthFilter.java:33)
      	at com.gearlaunch.hub.util.AbstractFilter.doFilter(AbstractFilter.java:48)
      	at com.voodoodyne.rollbar.AppengineRollbarFilter$TrappingFilterChain.doFilter(AppengineRollbarFilter.java:43)
      	at com.tapstream.rollbar.RollbarFilter.doFilter(RollbarFilter.java:37)
      	at com.voodoodyne.rollbar.AppengineRollbarFilter.doFilter(AppengineRollbarFilter.java:58)
      	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
      	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
      	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
      	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
      	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
      	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
      	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
      	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
      <continued in next message>
    W 13:23:32.675 <continued from previous message>
      	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
      	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
      	at org.mortbay.jetty.Server.handle(Server.java:326)
      	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
      	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
      	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
      	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
      	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
      	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
      	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
      	... 1 more
      Caused by: java.lang.NullPointerException
      	at com.paypal.base.util.ResourceLoader.searchClasspath(ResourceLoader.java:66)
      	at com.paypal.base.util.ResourceLoader.getInputStream(ResourceLoader.java:50)
      	at com.paypal.base.ConfigManager.<init>(ConfigManager.java:96)
      	at com.paypal.base.ConfigManager.getInstance(ConfigManager.java:116)
      	at com.paypal.base.SSLUtil.<clinit>(SSLUtil.java:65)
      	... 54 more
```

**Comment by juwlee** [comment]
Hi @stickfigure thanks for reporting the issue. It seems JRE on GAE does not have classpath defined. I will add a guard around the line that throws NPE.

**Comment by juwlee** [comment]
@stickfigure I pushed a fix which is available on branch `v1.2.6`. It would be great if you could test it out on your env.

**Comment by juwlee** [comment]
Closing due to inactivity. Please try the latest release and re-open if problem persists.

**Comment by stickfigure** [comment]
It works on GAE now. Thanks.
