### ISSUE TITLE
Why i am getting APIContext null?

### ISSUE THREAD

**Issue by esodot** [paypal/PayPal-Java-SDK#117]
Hello, 
im trying to test the application. Added my clientID and clientSecret from my Paypal Sandbox App to sdk_config.properties, but always get:

java.lang.IllegalArgumentException: APIContext cannot be null
        at com.paypal.api.payments.Payment.create(Payment.java:295)
        at com.paypal.api.payments.servlet.PaymentWithPayPalServlet.createPayment(PaymentWithPayPalServlet.java:198)
        at com.paypal.api.payments.servlet.PaymentWithPayPalServlet.doPost(PaymentWithPayPalServlet.java:78)
        at com.paypal.api.payments.servlet.PaymentWithPayPalServlet.doGet(PaymentWithPayPalServlet.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

That means SSLHandshake exception then i'm in debug mode. But why is that happen?? What i'm doing wrong?

Thank you so much for help!

esodot

**Comment by juwlee** [comment]
Hi @esodot the servlet holds an `APIContext` object that has `access token` to authorize Paypal API calls. (See [here](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/payments/servlet/PaymentWithPayPalServlet.java#L91). I suspect it is not getting access token and hence leaving `APIContext` empty.

- Can you try [a quick simple app](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/payments/util/GenerateAccessToken.java) that retrieves `access token`?
- How did you know it was SSLHandshake exception? If there is an exception that blocks communication, the access token call will fail for sure, let alone other API calls.

**Comment by juwlee** [comment]
Closing due to no activity.
