### ISSUE TITLE
Why doesn't return detail success response for 400 error

### ISSUE THREAD

**Issue by zeroro88** [paypal/PayPal-Java-SDK#122]
I generate a request have duplicate PayPal-Request-Id.
But use sdk I just get
"com.paypal.base.rest.PayPalRESTException: Response Code : 400 change log level to DEBUG for details."

I hope I can get

"{
  "name": "DUPLICATE_REQUEST_ID",
  "message": "The value of PayPal-Request-Id header has already been used",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DUPLICATE_REQUEST_ID",
  "debug_id": "4b55f789bf5d5"
}"

How can I get these detail message in code?
Thanks

**Comment by juwlee** [comment]
@zeroro88 this is one of improvements that we are hoping to add soon. It seems you are using the latest version, correct? Could you copy & paste the error dump here?

Also please see [here](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/HttpConnection.java#L139) for the current implementation. Catching `IOException` for `getInputStream()` and failing over to `getErrorStream()` seems to have [some caveats due to Java's implementation](http://stackoverflow.com/questions/6070350/errorstream-in-httpurlconnection). Something to think about.

**Comment by zeroro88** [comment]
@juwlee,
Thank you for your response.
Here is the error messages for duplicate request id, it just say 400 error, not easy for debug.
I suggest just invoke inputstreamToString on  [here](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/HttpConnection.java#L148) and [here](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/HttpConnection.java#L153) to show the detail respones will great
Another thing is hope sdk can provide a method to let user mask the sensitive info even for the sandbox mode.
```java
2015-08-28 17:27:51,156 DEBUG  [HttpConnection.executeWithStream] curl command: 
curl -v 'https://api.sandbox.paypal.com/v1/payments/payment' \
-H "Authorization: Bearer xxxxxx" \
-H "User-Agent: PayPalSDK/PayPal-Java-SDK 1.2.8 (lang=Java;v=1.7.0_75;bit=64;os=Windows_8.1 6.3)" \
-H "PayPal-Request-Id: 1" \
-H "Content-Type: application/json" \
-d '{
  "intent": "sale",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [
      {
        "credit_card": {
          "number": "5500005555555559",
          "type": "mastercard",
          "expire_month": 11,
          "expire_year": 2018,
          "cvv2": 111,
          "first_name": "Joe",
          "last_name": "Shopper"
        }
      }
    ]
  },
  "transactions": [
    {
      "amount": {
        "currency": "USD",
        "total": "123"
      },
      "description": "This is the payment transaction description."
    }
  ]
}'
com.paypal.base.rest.PayPalRESTException: Response Code : 400 change log level to DEBUG for details.
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:438)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:266)
	at com.paypal.api.payments.Payment.create(Payment.java:307)
	at com.xxxxx.paypal.PaypalClient.payment(PaypalClient.java:161)
	at com.xxxxx.paypal.PaypalClientTest.testPayment(PaypalClientTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by juwlee** [comment]
The fix has been merged and will be shipped in the upcoming release.

**Comment by togaurav** [comment]
I am also getting 400 error, surprising thing is the error is not consistent, sometime I get error 400, sometime junit tests pass successfully , any idea why is it so?

**Comment by juwlee** [comment]
@togaurav are you calling the same API for the same account?

**Comment by togaurav** [comment]
yes, we have some bunch of junit tests that verifies our integration with payapl, we are using sandbox paypal account for testing, we are getting Error 400 sometimes when we make direct call to paypal api for payment.

**Comment by juwlee** [comment]
Can you share debug IDs from failures and successes?

**Comment by dlogger** [comment]
>>com.paypal.base.rest.PayPalRESTException: Response Code : 400 change log level to DEBUG for details.
>The fix has been merged and will be shipped in the upcoming release.

I assume that this wasn't shipped yet, right?
If so, when will it be shipped?

Thanks much

**Comment by togaurav** [comment]
**Please find the detail that I collected from paypal sandbox console:**

## MetaData

{
"url": "/v1/payments/payment",
"create_time": "2015-10-01T08:21:14Z",
"additional_properties": {},
"account_number": "2112703502376077204",
"client_id": "AZe3YVV6eONU4QqC-YJw1elPwHuUGwMoUapg_H7KPDWU5IUboDyahOCDoOgo04y9RuBTK6m_TzDzngn8",
"id": "560cecfb36b75d4776921a9f"
}

## Request:

{
"body": {
"intent": "sale",
"payer": {
"payment_method": "credit_card",
"funding_instruments": [
{
"credit_card": {
"first_name": "John Doe",
"expire_month": 4,
"number": "xxxxxxxxxxxx5105",
"cvv2": "**",
"expire_year": 2018,
"type": "visa"
}
}
]
},
"transactions": [
{
"amount": {
"currency": "USD",
"total": "21.29"
}
}
]
},
"header": {
"x-pp-ads-performed": "false",
"content-length": "460",
"paypal-request-id": "2dc480f7-66e8-4bf2-87e0-ee93db9526a3",
"x-pp-silover": "name%3DSANDBOX3.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D4209773654",
"connection": "keep-alive",
"accept": "text/html, image/gif, image/jpeg, *; q\u003d.2, */; q\u003d.2",
"client-auth": "No cert",
"host": "api.sandbox.paypal.com",
"user-agent": "PayPalSDK/PayPal-Java-SDK 1.2.8 (lang\u003dJava;v\u003d1.7.0_45;bit\u003d64;os\u003dWindows_8 6.2)",
"authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx2dZ8",
"x-pp-corrid": "9ebc4647bd344",
"pp_remote_addr": "106.51.225.141",
"content-type": "application/json",
"x-pp-slingshot-targetapp": "platformapiserv"
},
"additional_properties": {},
"method": "POST"
}

## Response:

{
"status": 400,
"duration_time": 735,
"body": {
"message": "An unknown error has occurred",
"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR",
"name": "UNKNOWN_ERROR",
"debug_id": "9ebc4647bd344"
},
"additional_properties": {},
"header": {
"Content-Length": "185",
"Content-Language": "*",
"CORRELATION-ID": "9ebc4647bd344",
"Date": "Thu, 01 Oct 2015 08:21:15 GMT",
"Connection": "close",
"Paypal-Debug-Id": "9ebc4647bd344",
"PROXY_SERVER_INFO": "host\u003dslcsbplatformapiserv3001.slc.paypal.com;threadId\u003d423",
"Content-Type": "application/json"
}
}

**Comment by dlogger** [comment]
Any news on this?
