### ISSUE TITLE
mvn package 

### ISSUE THREAD

**Issue by ara0** [paypal/PayPal-Java-SDK#142]
just download PayPal-Java-SDK-master.zip and try mvn package 

13:56:19.597 [pool-4-thread-1] ERROR com.paypal.base.rest.PayPalResource - File doesn't exist: C:\PayPal-Java-SDK-master\rest-api-sdk\unknown.properties
java.io.FileNotFoundException: File doesn't exist: C:\PayPal-Java-SDK-master\rest-api-sdk\unknown.properties
        at com.paypal.base.rest.PayPalResource.initConfig(PayPalResource.java:73) [classes/:?]
        at com.paypal.api.payments.RefundTestCase.testRefundUnknownFileConfiguration(RefundTestCase.java:108) [test-classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_51]
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80) [testng-6.3.1.jar:?]
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:691) [testng-6.3.1.jar:?]
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883) [testng-6.3.1.jar:?]
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208) [testng-6.3.1.jar:?]
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng-6.3.1.jar:?]
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng-6.3.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_51]
        at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]
13:56:19.597 [pool-4-thread-1] ERROR com.paypal.base.rest.PayPalResource - File doesn't exist: C:\PayPal-Java-SDK-master\rest-api-sdk\unknown.properties
java.io.FileNotFoundException: File doesn't exist: C:\PayPal-Java-SDK-master\rest-api-sdk\unknown.properties
        at com.paypal.base.rest.PayPalResource.initConfig(PayPalResource.java:73) [classes/:?]
        at com.paypal.api.payments.SaleTestCase.testSaleUnknownFileConfiguration(SaleTestCase.java:171) [test-classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_51]
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80) [testng-6.3.1.jar:?]
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:691) [testng-6.3.1.jar:?]
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883) [testng-6.3.1.jar:?]
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208) [testng-6.3.1.jar:?]
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng-6.3.1.jar:?]
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng-6.3.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_51]
        at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]
13:56:19.659 [pool-4-thread-1] DEBUG com.paypal.base.HttpConnection - curl command:
curl -v 'https://api.sandbox.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-a5cafa77' \
-H "Host: api.sandbox.paypal.com" \
-d ''

**Comment by juwlee** [comment]
Hi @ara0 it looks like [a negative test case](https://github.com/paypal/PayPal-Java-SDK/blob/5e7eb6234159ce94891ea454140c0e85a5cf1133/rest-api-sdk/src/test/java/com/paypal/base/rest/PayPalResourceTestCase.java#L15) which seems to be working fine. Any reason you are trying to compile source code yourself?
