### ISSUE TITLE
Set custom SSLContext to connections

### ISSUE THREAD

**Issue by leandrohsilveira** [paypal/PayPal-Java-SDK#143]
Hello, I work for the "Bry Tecnologia S/A" in Brazil.

First, I apologize for my English.

So we have a web application that we are integrating with PayPal, however this application also uses an internal web service that is legacy.
This web service requires an SSL configuration with a certificate issued from an internal authority that can not be accepted by PayPal.

Our problem is that the Client of this legacy web service configures SSL for connection through the Java System properties, which are:

"javax.net.ssl.keyStore"
"javax.net.ssl.keyStorePassword"
"javax.net.ssl.trustStore"
"javax.net.ssl.trustStorePassword"

We have simulated this scenario and at first, integration with PayPal works until the legacy web service is accessed, resulting in the following error:

```java

com.paypal.base.exception.HttpErrorException: retry fails..  check log for more information
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:197) [rest-api-sdk-1.4.1.jar:1.4.1]
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:67) [rest-api-sdk-1.4.1.jar:1.4.1]
	at com.paypal.base.rest.OAuthTokenCredential.generateOAuthToken(OAuthTokenCredential.java:228) [rest-api-sdk-1.4.1.jar:1.4.1]
	... 110 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_75]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_75]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_75]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [rt.jar:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676) [rt.jar:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674) [rt.jar:1.7.0_75]
	at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672) [rt.jar:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245) [rt.jar:1.7.0_75]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468) [rt.jar:1.7.0_75]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) [rt.jar:1.7.0_75]
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:160) [rest-api-sdk-1.4.1.jar:1.4.1]
	... 112 more
```

If I clean the system properties mentioned above, the integration works correctly, however can cause problems with simultaneous access to PayPal and legacy web service. If two users almost simultaneously access both services, one of them will have an error. Or the legacy service will not have a certificate in System Properties to configure the connection, or PayPal will charge handshake error.

Ok, we know that our service is wrong in using the properties of the VM to configure SSL channel. But adjusting the client API of our legacy web service to set up a "SSLContext" require an almost complete refactoring of the Client. In 2016, we will start a new version of this web service which I have requested the fix

So I wonder if you can apply an improvement that will allow the integrated application set a "SSLContext" for the "REST API SDK" use in all connections.

If so, when this improvement will be available?

As our time is short, I did checkout the stable branch and adjusted as follows:

* DefaultHttpConnection: 

```java

public class DefaultHttpConnection extends HttpConnection {

	/**
	 * Secure Socket Layer context
	 */
	private SSLContext sslContext;

	public DefaultHttpConnection() {
		try {
			sslContext = SSLUtil.getSSLContext(null);
		} catch (SSLConfigurationException e) {
			throw new RuntimeException(e);
		}
	}
        
	/* Just added this constructor */
	public DefaultHttpConnection(SSLContext sslContext) {
		this.sslContext = sslContext;
	}

	[...]
}
```

* ConnectionManager:

```java

public final class ConnectionManager {

	[...]

	private SSLContext customSslContext;

	[...]

	/**
	 * @return HttpConnection object
	 */
	public HttpConnection getConnection() {
		/* Test if the custom ssl context is set, if not, keep it working as it already works. */
		if (customSslContext != null) {
			return new DefaultHttpConnection(customSslContext);
		} else {
			return new DefaultHttpConnection();
		}
	}

	/**
	 * Overloaded method used factory to load GoogleAppEngineSpecific connection
	 *
	 * @param httpConfig
	 *            {@link HttpConfiguration} object
	 * @return {@link HttpConnection} object
	 */
	public HttpConnection getConnection(HttpConfiguration httpConfig) {

		if (httpConfig.isGoogleAppEngine()) {
			return new GoogleAppEngineHttpConnection();
		} else {
			/* Adjusted here */
			return getConnection();
		}
	}

	/* Added this method. */
	public void configureCustomSslContext(SSLContext sslContext) {
		customSslContext = sslContext;
	}

}

```

I chose this way to make minimal changes to the API... is there any other way to solve this situation without changes in the API?

In this way, our legacy web service is free to set the properties without affecting the integration because now I can set a SSLContext with a certificate from an authority that PayPal trust. :)

**Comment by juwlee** [comment]
Hi @leandrohsilveira since you already have the code change, can you please submit it in the form of pull request? That will make code review much easier. Then we can discuss more in the PR.

**Comment by juwlee** [comment]
Re-opening issue for the PR #144

**Comment by juwlee** [comment]
Closing as the corresponding PR #144 has been merged. Thanks again @leandrohsilveira !
