### ISSUE TITLE
Paypal java rest api integration issues 

### ISSUE THREAD

**Issue by vignesh001** [paypal/PayPal-Java-SDK#158]
I have integrated paypal gateway with java rest api to my website 
successfully.It went fine for some time, But unfortunately i got issue 
while getting access code now.I already raised ticket 2 times but i can not find out the problem excatly what causes the problem in integration. 

Thanks in advance.

You can check my code here :

```java
Map<String, String> sdkConfig = new HashMap<String, String>();
sdkConfig.put("mode", "sandbox");
System.out.println("--------------- Paypal Test -------------------");
String accessToken = new OAuthTokenCredential("<ClientID>", "<SecretKey>").getAccessToken();
APIContext apiContext = new APIContext(accessToken);
apiContext.setConfigurationMap(sdkConfig);

Amount amount = new Amount();
amount.setCurrency("USD");
amount.setTotal("12");

Transaction transaction = new Transaction();
transaction.setDescription("creating a payment");

List<Item> itemList=new ArrayList<Item>();
ItemList items=new ItemList();

Item item=new Item();
item.setName("Cart");
item.setQuantity("1"); 
item.setPrice("12");
item.setCurrency("USD");
//item.setSku(shoppingProduct.getUnit());
itemList.add(item);
items.setItems(itemList);
transaction.setItemList(items);
transaction.setAmount(amount);

List<Transaction> transactions = new ArrayList<Transaction>();
transactions.add(transaction);
Payer payer = new Payer();
payer.setPaymentMethod("paypal");

Payment payment = new Payment();
payment.setIntent("sale");
payment.setPayer(payer);
payment.setTransactions(transactions);
RedirectUrls redirectUrls = new RedirectUrls();
redirectUrls.setCancelUrl("cancel url");
redirectUrls.setReturnUrl("return url");
payment.setRedirectUrls(redirectUrls);
Payment createdPayment = payment.create(apiContext); 

Iterator<Links> links1 = createdPayment.getLinks().iterator();
while (links1.hasNext()) {
  Links link = links1.next();
  if (link.getRel().equalsIgnoreCase("approval_url")) {
    request.setAttribute("redirectURL", link.getHref());
  }
}
request.setAttribute("response", com.paypal.api.payments.Payment.getLastResponse()); 

String output=com.paypal.api.payments.Payment.getLastResponse();
String redirectURL=null;
try {
  JSONObject json=new JSONObject(output);

  JSONArray links=json.getJSONArray("links");

  for(int i=0;i<links.length();i++ ){
    JSONObject hrefObj=links.getJSONObject(i);
    String str=hrefObj.getString("method");
    if(str.equalsIgnoreCase("REDIRECT")){
      redirectURL=hrefObj.getString("href");
    }
  }
} catch (JSONException e) {
  e.printStackTrace();
```

Error Log Information:
-----------------------------
```
com.paypal.exception.HttpErrorException: retry fails.. check log for more information
at com.paypal.core.HttpConnection.execute(HttpConnection.java:139)
at com.paypal.core.rest.OAuthTokenCredential.generateOAuthToken(OAuthTokenCredential.java:192)
at com.paypal.core.rest.OAuthTokenCredential.generateAccessToken(OAuthTokenCredential.java:148)
at com.paypal.core.rest.OAuthTokenCredential.getAccessToken(OAuthTokenCredential.java:126)
at com.thendral.controller.ThendralController.paypalRequest(ThendralController.java:9549)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Unknown Source)
```

**Comment by pp-randy** [comment]
@vignesh001 I've had some success also passing in the config map to the OAuthTokenCredential constructor with your code example:
String accessToken = new OAuthTokenCredential("<ClientID>", "<SecretKey>", sdkConfig).getAccessToken();

Your cart totals don't match here:
amount.setTotal("1");
item.setPrice("12");

**Comment by vignesh001** [comment]
@pp-randy  I have some problem still.I am using paypal-core-1.6.2.jar dependency. can you please provide sample java api to make payment.i tried lot in paypal documentation but can't to figure out the correct java rest api.

**Comment by pp-randy** [comment]
@vignesh001 for the most part your code is working for me but I modified it to run in the console.  To add you still need apiContext.setConfigurationMap(sdkConfig); from your original code.  

What error are you getting now?  Are you at least getting a connection to the PayPal servers?  

`public static void main(String[] args) throws PayPalRESTException {
		
		Map<String, String> sdkConfig = new HashMap<String, String>();
		sdkConfig.put(Constants.MODE, Constants.SANDBOX);

		String clientId = "";
	        String clientSecret = "";
				
		String accessToken = new OAuthTokenCredential(clientId, clientSecret, sdkConfig).getAccessToken();
		
		APIContext apiContext = new APIContext(accessToken);
		System.out.println(accessToken);
                // still need to toss in the sdkConfig here
		apiContext.setConfigurationMap(sdkConfig); 

		Amount amount = new Amount();
		amount.setCurrency("USD");
		amount.setTotal("1");

		Transaction transaction = new Transaction();
		transaction.setDescription("creating a payment");

		List itemList=new ArrayList();
		ItemList items=new ItemList();

		Item item=new Item();
		item.setName("Cart");
		item.setQuantity("1"); 
		item.setPrice("1");
		item.setCurrency("USD");
		//item.setSku(shoppingProduct.getUnit());
		itemList.add(item);
		items.setItems(itemList);
		transaction.setItemList(items);
		transaction.setAmount(amount);

		List transactions = new ArrayList();
		transactions.add(transaction);
		Payer payer = new Payer();
		payer.setPaymentMethod("paypal");

		Payment payment = new Payment();
		payment.setIntent("sale");
		payment.setPayer(payer);
		payment.setTransactions(transactions);
		RedirectUrls redirectUrls = new RedirectUrls();
		redirectUrls.setCancelUrl("https://return.com");
		redirectUrls.setReturnUrl("https://return.com");
		payment.setRedirectUrls(redirectUrls);
		try {
			
			Payment createdPayment = payment.create(apiContext);
                        System.out.println(createdPayment.getId());
			String output=com.paypal.api.payments.Payment.getLastResponse();
			System.out.println(output);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}`

**Comment by pp-randy** [comment]
@vignesh001 This PayPal-Java-SDK does not use the sdk-core.  You should have a rest-api-sdk-1.4.1.jar.

**Comment by vignesh001** [comment]
i already added rest-api-sdk 0.7.1 jar . i can't connect with paypal server. same error i am getting .

error code:

Exception in thread "main" com.paypal.core.rest.PayPalRESTException: retry fails..  check log for more information
	at com.paypal.core.rest.OAuthTokenCredential.generateOAuthToken(OAuthTokenCredential.java:201)
	at com.paypal.core.rest.OAuthTokenCredential.generateAccessToken(OAuthTokenCredential.java:148)
	at com.paypal.core.rest.OAuthTokenCredential.getAccessToken(OAuthTokenCredential.java:126)
	at SubScribe.main(SubScribe.java:31)
Caused by: com.paypal.exception.HttpErrorException: retry fails..  check log for more information
	at com.paypal.core.HttpConnection.execute(HttpConnection.java:139)
	at com.paypal.core.rest.OAuthTokenCredential.generateOAuthToken(OAuthTokenCredential.java:192)
	... 3 more


![image](https://cloud.githubusercontent.com/assets/17721368/13672952/fce17cb6-e6fc-11e5-80cf-52581d1cc531.png)


![image](https://cloud.githubusercontent.com/assets/17721368/13672964/0e4ea56e-e6fd-11e5-89bf-9386ecbd1f6a.png)

**Comment by pp-randy** [comment]
This looks more like a connectivity issue.  Can you switch to Production, use your Sandbox Credentials to force an error, and see if you are able to connect to Production servers?

**Comment by pp-randy** [comment]
Here is an article on timeouts that could also be helpful https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1403&expand=true&locale=en_US

**Comment by jaypatel512** [comment]
Hey @vignesh001 ! 

If your application has maven and pom.xml setup, can you please use the following dependency and check again. You seem to be using pretty old JAR, that may not be supporting TLS connections. Older versions of this SDK is not supported anymore since the POODLE attack.

Try using:

```
<dependency>
    <groupId>com.paypal.sdk</groupId>
    <artifactId>rest-api-sdk</artifactId>
    <version>1.4.1</version>
</dependency>
```

You can replace 1.4.1 to LATEST if you wish. Try this and see.

**Comment by jaypatel512** [comment]
Alternatively, you can download the JAR from here: http://mvnrepository.com/artifact/com.paypal.sdk/rest-api-sdk/1.4.1

**Comment by jaypatel512** [comment]
Hey @vignesh001 !

Any success ? Please let me know if that solved your issue, so that we can solve the issue and consider the last comments as the correct answer. 

Thanks.

**Comment by vignesh001** [comment]
@pp-randy  i switched my sandbox account to production mode but same issue i am facing again  

error code:

Mar 14, 2016 11:33:29 AM com.paypal.core.LoggingManager log
SEVERE:  Retry  No : 1...
Mar 14, 2016 11:33:30 AM com.paypal.core.LoggingManager log
SEVERE: Caught exception while handling error response
Mar 14, 2016 11:33:30 AM com.paypal.core.LoggingManager log
SEVERE:  Retry  No : 2...
Exception in thread "main" com.paypal.core.rest.PayPalRESTException: retry fails..  check log for more information
	at com.paypal.core.rest.OAuthTokenCredential.generateOAuthToken(OAuthTokenCredential.java:201)
	at com.paypal.core.rest.OAuthTokenCredential.generateAccessToken(OAuthTokenCredential.java:148)
	at com.paypal.core.rest.OAuthTokenCredential.getAccessToken(OAuthTokenCredential.java:126)
	at PaymentTest.main(PaymentTest.java:98)
Caused by: com.paypal.exception.HttpErrorException: retry fails..  check log for more information
	at com.paypal.core.HttpConnection.execute(HttpConnection.java:139)
	at com.paypal.core.rest.OAuthTokenCredential.generateOAuthToken(OAuthTokenCredential.java:192)
	... 3 more

**Comment by vignesh001** [comment]
@jaypatel512  i configured rest api sdk 1.4.1 jar but create payment api throwing compile time error.

 Payment createdPayment = payment.create(apiContext);

error: change type of api context to string.

**Comment by pp-randy** [comment]
Can you try to clean the project in Eclipse (Project -> Clean...)?  I am wondering if this method isn't being picked up  https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/Payment.java#L470 

There is a create that expects a string the Access Token, but this linked above does expect the APIContext.

**Comment by juwlee** [comment]
@vignesh001 are you still experiencing the issue? Can you please post the error you are getting and the code that is throwing it if you are still seeing one? As @pp-randy said, the `create(apiContext)` method does not look like being picked up. The method has been there since a very old version of the SDK, so it might be an environment-related issue rather than code issue. Also, can you show how you got the `error: change type of api context to string` error message?

**Comment by juwlee** [comment]
Closing due to inactivity. @vignesh001 please feel free to reopen or let us know if you still see the issue. Trying `curl` might be able to tell you whether it is an SDK or an API issue.

**Comment by vignesh001** [comment]
@juwlee I am getting same exception. i checked my firewall settings, cleaned the project and i tried in new environment too. No luck. Same problem i am facing. 

Can any one provide me the modified working code what i already i posted with dependency.

Thanks in Advance.

**Comment by juwlee** [comment]
@vignesh001 what error are you seeing now? Have you tried `curl` and see if it works?

**Comment by vignesh001** [comment]
@juwlee  i am not aware of curl language and api

**Comment by juwlee** [comment]
Please see the right hand side of [API reference docs](https://developer.paypal.com/docs/api/#create-a-payment) which shows `curl` examples. There is also [OAuth samples](https://developer.paypal.com/docs/api/#authentication--headers) to get an access token.

**Comment by juwlee** [comment]
Closing as there has been no activity for some time. Please feel free to add a comment or re-open.

**Comment by thivi90** [comment]
I too got the same connection exception..

com.paypal.core.rest.PayPalRESTException: Received fatal alert: handshake_failure
	at com.paypal.core.rest.OAuthTokenCredential.generateOAuthToken(OAuthTokenCredential.java:141)
	at com.paypal.core.rest.OAuthTokenCredential.generateAccessToken(OAuthTokenCredential.java:95)
	at com.paypal.core.rest.OAuthTokenCredential.getAccessToken(OAuthTokenCredential.java:86)
	at com.paypal.util.EncryptionUtil.main(EncryptionUtil.java:141)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)....

May be because of java version 1.6. It couldn't connect through TLSv1.2
Does anybody know how to fix this for java 1.6?

**Comment by pp-randy** [comment]
@thivi90 take a look here: https://github.com/paypal/tls-update#java 

Looks like you should be able to, but you might need to update your Java 1.6 to 6u115 b32
http://www.oracle.com/technetwork/java/javase/documentation/overview-156328.html#6u115-b32

**Comment by thivi90** [comment]
It works only for Java 1.8,
for java 1.6 6u115 or even 1.7 the same handshake_failure..

**Comment by hakkinepally** [comment]
yes, That is correct. For JDK 1.6 Version. I am running into same Issue. Is there any resolution. Please help me.

**Comment by thivi90** [comment]
use at least java version 6u115 and use paypal-core-1.7.0.jar.It will work!

**Comment by hakkinepally** [comment]
I am using REST API SDK 1.2.9 version with JDK 1.6. do I still need to use paypal-core-1.7.0 on top of it ?

**Comment by thivi90** [comment]
yes, if you want to use JDK 1.6 else you need to use JDK 1.8!

**Comment by jaypatel512** [comment]
I would highly recommend updating to the latest version of the SDK. We have proper bug fixes, as well as many more improvements to the integration style starting from version [1.8.0](https://github.com/paypal/PayPal-Java-SDK/releases/tag/v1.8.0). 

in version v1.8.0, you do not need the paypal-core-sdk at all.
