### ISSUE TITLE
Issues with invoicing - SocketTimeoutException

### ISSUE THREAD

**Issue by ampatalas** [paypal/PayPal-Java-SDK#159]
I'm trying to create an invoice and send it to user.
I'm running my application locally on Tomcat, and I'm using the Sandbox Environment. 

```java
RequestEnvelope requestEnvelope = new RequestEnvelope();
requestEnvelope.setErrorLanguage("en_US");

List<InvoiceItemType> invoiceItemList = new ArrayList<InvoiceItemType>();
InvoiceItemType invoiceItem =
new InvoiceItemType(itemName, Double.parseDouble("1"), itemValue);
invoiceItemList.add(invoiceItem);
        InvoiceItemListType itemList = new InvoiceItemListType(invoiceItemList);

        InvoiceType invoice = new InvoiceType(merchantEmail, customerEmail, itemList, "USD");

        CreateAndSendInvoiceRequest createAndSendInvoiceRequest =
                        new CreateAndSendInvoiceRequest(requestEnvelope, invoice);

        InvoiceService service = null;
        try {
            InputStream stream = PayPalServiceImpl.class.getResourceAsStream("/sdk_config.properties");
            service = new InvoiceService(stream);
        } catch (IOException e) {
            mailService.sendLog("Error Message : " + e.getMessage());
        }
        CreateAndSendInvoiceResponse createAndSendInvoiceResponse = null;
        try {
            //HERE IT FAILS
            createAndSendInvoiceResponse =
                            service.createAndSendInvoice(createAndSendInvoiceRequest);
        } catch (Exception e) {
            mailService.sendLog("Error Message : " + e.getMessage());
        }
```
```
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_25]
	at java.net.SocketInputStream.read(Unknown Source) ~[na:1.8.0_25]
	at java.net.SocketInputStream.read(Unknown Source) ~[na:1.8.0_25]
	at sun.security.ssl.InputRecord.readFully(Unknown Source) ~[na:1.8.0_25]
	at sun.security.ssl.InputRecord.read(Unknown Source) ~[na:1.8.0_25]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[na:1.8.0_25]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source) ~[na:1.8.0_25]
	at sun.security.ssl.AppInputStream.read(Unknown Source) ~[na:1.8.0_25]
	at java.io.BufferedInputStream.fill(Unknown Source) ~[na:1.8.0_25]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[na:1.8.0_25]
	at java.io.BufferedInputStream.read(Unknown Source) ~[na:1.8.0_25]
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source) ~[na:1.8.0_25]
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source) ~[na:1.8.0_25]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_25]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_25]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[na:1.8.0_25]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[na:1.8.0_25]
	at com.paypal.core.HttpConnection.execute(HttpConnection.java:91) ~[paypal-core-1.7.0.jar:na]
	... 93 common frames omitted
```

I've seen this Exception in other issues, but this is not load testing, I'm just trying to get sending the invoice to work.

The proxy configuration in my sdk_config.properties is commented out.

**Comment by pp-randy** [comment]
Hi @ampatalas  can you please create your issue under the invoice-sdk-java repository? 
https://github.com/paypal/invoice-sdk-java

The PayPal-Java-SDK supports invoicing but over the REST API, appears you are using the above Classic SOAP integration.
