### ISSUE TITLE
invoice.create(accessToken) issue

### ISSUE THREAD

**Issue by marc0w** [paypal/PayPal-Java-SDK#169]
I have a problem with the create() method of the sample. I call create() like this

		Map<String, String> map = new HashMap<String, String>();
		map.put("mode", "sandbox");
		map.put("acct1.UserName", "paypal-facilitator_api1.[REPLACED].com"); 
		map.put("acct1.Password", "[REPLACED]");
		map.put("acct1.Signature", "[REPLACED]");
		map.put("acct1.AppId", "APP-80W284485P519543T");
		try {
			accessToken = new OAuthTokenCredential("[REPLACED]", "[REPLACED]", map).getAccessToken();
		} catch (PayPalRESTException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		System.out.println(accessToken);
		InvoiceSample invoiceSample = new InvoiceSample();
		Invoice invoice = invoiceSample.create();

My accessToken starts like this : 

> Bearer A101....

What am i doing wrong? I use the json file of the sample folder. I get the following exception:

> response-code: 0	details: null
> 	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:441)
> 	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:267)
> 	at com.paypal.api.payments.Invoice.create(Invoice.java:547)
> 	at com.paypal.api.payments.Invoice.create(Invoice.java:523)
> 	at de.ernst.main.InvoiceSample.create(InvoiceSample.java:79)
> 	at de.ernst.main.InvoiceSample.main(InvoiceSample.java:48)
> Caused by: java.net.MalformedURLException
> 	at java.net.URL.<init>(Unknown Source)
> 	at java.net.URL.<init>(Unknown Source)
> 	at java.net.URL.<init>(Unknown Source)
> 	at com.paypal.base.DefaultHttpConnection.createAndconfigureHttpConnection(DefaultHttpConnection.java:59)
> 	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:406)
> 	... 5 more
> Caused by: java.lang.NullPointerException
> 	... 10 more

**Comment by marc0w** [comment]
Issue #168 fixed my problem! 

Just added Invoice.initConfig(...); and it works
