### ISSUE TITLE
Tokeninfo "client id or secret is null"

### ISSUE THREAD

**Issue by wwatroba** [paypal/PayPal-Java-SDK#173]
### General Information

- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs): 3c65a55c453d4
- Version of Java used: 1.8.0_77
- SDK Version: 1.4.2

### Issue Description

I've got problem with method Tokeninfo.createFromAuthorizationCode.
In Sandbox mode everything is OK, but after switching to Live mode I receive
````
com.paypal.base.rest.PayPalRESTException: Error code : 400 with response : {"error_description":"client id or secret is null","error":"invalid_client","correlation_id":"3c65a55c453d4","information_link":"https://developer.paypal.com/docs/api/#errors"}
	at com.paypal.base.rest.PayPalRESTException.createFromHttpErrorException(PayPalRESTException.java:72)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:439)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:267)
	at com.paypal.api.openidconnect.Tokeninfo.createFromAuthorizationCodeParameters(Tokeninfo.java:254)
	at com.paypal.api.openidconnect.Tokeninfo.createFromAuthorizationCode(Tokeninfo.java:194)
	at controllers.saas.PaymentController.returnUrl(PaymentController.java:189)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$80$$anonfun$apply$80.apply(Routes.scala:2098)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$80$$anonfun$apply$80.apply(Routes.scala:2098)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
Caused by: com.paypal.base.exception.HttpErrorException: Error code : 400 with response : {"error_description":"client id or secret is null","error":"invalid_client","correlation_id":"3c65a55c453d4","information_link":"https://developer.paypal.com/docs/api/#errors"}
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:174)
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:67)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:425)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:267)
	at com.paypal.api.openidconnect.Tokeninfo.createFromAuthorizationCodeParameters(Tokeninfo.java:254)
	at com.paypal.api.openidconnect.Tokeninfo.createFromAuthorizationCode(Tokeninfo.java:194)
	at controllers.saas.PaymentController.returnUrl(PaymentController.java:189)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$80$$anonfun$apply$80.apply(Routes.scala:2098)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$80$$anonfun$apply$80.apply(Routes.scala:2098)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.paypal.com/v1/identity/openidconnect/tokenservice
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.paypal.com/v1/identity/openidconnect/tokenservice
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:133)
```


I think problem is in class HttpConnection. Method setHttpHeaders is called only in sandbox mode.

**Comment by pp-randy** [comment]
Can you try setting both your **mode** and **endpoint** configurations to live values? 

I found a similar issue here and changing both of those configuration values was the suggestion https://github.com/paypal/PayPal-Java-SDK/issues/138.

**Comment by wwatroba** [comment]
It did not work. Still the same problem.

sdk_config.properties:

mode = live 
clientId=...
clientSecret=...
service.EndPoint=https://api.paypal.com

code:

            Map<String, String> configurationMap = new HashMap<String, String>();
            configurationMap.put(Constants.MODE, PayPalResource.getConfigurations().get(Constants.MODE));
            configurationMap.put(Constants.CLIENT_ID, PayPalResource.getClientID());
            configurationMap.put(Constants.CLIENT_SECRET, PayPalResource.getClientSecret());
            configurationMap.put(Constants.ENDPOINT, PayPalResource.getConfigurations().get(Constants.ENDPOINT));

            APIContext apiContext = new APIContext();
            apiContext.setConfigurationMap(configurationMap);

            CreateFromAuthorizationCodeParameters param = new CreateFromAuthorizationCodeParameters();
            param.setClientID(PayPalResource.getClientID());
            param.setClientSecret(PayPalResource.getClientSecret());
            param.setCode(code);

            Tokeninfo info = Tokeninfo.createFromAuthorizationCode(apiContext, param);

**Comment by jaypatel512** [comment]
Can you please confirm if `PayPalResource.getClientID()` returns valid clientId.

**Comment by wwatroba** [comment]
Yes, it return valid clientId. 
In sandbox everything works ok. 
In live mode after change HttpConnection:102 to `if (headers != null) {` also works.

**Comment by jaypatel512** [comment]
Hey @wwatroba !

I think the culprit is at : https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/HttpConnection.java#L109

We `setHeaders(headers);` inside that if string. I am assuming, that is the reason why it is working fine in sandbox, but in live, that code wont work because of the if condition. 

Can you please double check and confirm if by moving `setHeaders(headers)` method as shown below works:
```java
			//Place setHttpHeaders method here
			setHttpHeaders(headers);
			String mode = ConfigManager.getInstance().getConfigurationMap()
					.get(Constants.MODE);
			if (headers != null && !Constants.LIVE.equalsIgnoreCase(mode)) {
				String cmd = "curl command: \n";
				cmd += "curl -v '" + connection.getURL().toString() + "' \\\n";
				Iterator<String> keyIter = headers.keySet().iterator();
				while (keyIter.hasNext()) {
					String key = keyIter.next();
					String value = headers.get(key);
					cmd += "-H \"" + key + ": " + value + "\" \\\n";
				}
				cmd += "-d '" + payload + "'";
				log.debug(cmd);
			}
```

**Comment by wwatroba** [comment]
Moving `setHeaders` ouside `if` solves the problem.

**Comment by jaypatel512** [comment]
Thanks @wwatroba for testing this out. I will go ahead and make the change, and get that released in next release, which should be soon.
