### ISSUE TITLE
Getting UNKNOWN_ERROR on Authorization and Sale attempt

### ISSUE THREAD

**Issue by jamesmjones00123** [paypal/PayPal-Java-SDK#194]
This is in Sandbox. When I try a sale or authorization with a VALID CC number I get:

```
response-code: 400	details: name: UNKNOWN_ERROR	message: An unknown error has occurred	details: null	debug-id: e5f28243a9d0a	information-link: https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR
	at com.paypal.base.rest.PayPalRESTException.createFromHttpErrorException(PayPalRESTException.java:73)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:441)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:269)
	at com.paypal.api.payments.Payment.create(Payment.java:484)
	at com.serviceproviders.Paypal.processAuthorization(Paypal.java:235)
	at com.objects.Billing.processAuthorization(Billing.java:83)
	at com.test.TestHarness.main(TestHarness.java:34)
Caused by: com.paypal.base.exception.HttpErrorException: Error code : 400 with response : {"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"e5f28243a9d0a"}
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:174)
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:67)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:427)
	... 5 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.sandbox.paypal.com/v1/payments/payment
```
But what is interesting is that if I make the CC number incorrect it fails and gives me a correct error message: 

```
response-code: 400	details: name: VALIDATION_ERROR	message: Invalid request - see details	details: [{
  "field": "payer.funding_instruments[0].credit_card.number",
  "issue": "Value is invalid"
}]
```

So I am talking to the back end OK it appears. Environment is as follows:

```
		<dependency>
			<groupId>com.paypal.sdk</groupId>
			<artifactId>rest-api-sdk</artifactId>
			<version>1.6.0</version>
		</dependency>
```

```
# Connection Information
http.ConnectionTimeOut=5000
http.Retry=1
http.ReadTimeOut=30000
http.MaxConnection=100

# HTTP Proxy configuration
# If you are using proxy set http.UseProxy to true and replace the following values with your proxy parameters
http.ProxyPort=8080
http.ProxyHost=127.0.0.1
http.UseProxy=false
http.ProxyUserName=null
http.ProxyPassword=null

#Set this property to true if you are using the PayPal SDK within a Google App Engine java app
http.GoogleAppEngine = false

# Service Configuration
service.EndPoint=https://api.sandbox.paypal.com
# Live EndPoint
# service.EndPoint=https://api.paypal.com

# Credentials
clientId=AcD8V2s............removed.............................................................
clientSecret=EBpT...........removed.............................................................

# Webhook Validation
#webhook.trustCert=DigiCertSHA2ExtendedValidationServerCA.crt
```

```
	public static String processAuthorization(Billing b, String amountToCharge) {
		Payment createdPayment = null;
		try {
			OAuthTokenCredential tokenCredential = Payment.initConfig(new File("src/paypal.properties"));
			String accessToken = tokenCredential.getAccessToken();		
			// ###Address
			// Base Address object used as shipping or billing
			// address in a payment. [Optional]
			Address billingAddress = new Address();
			billingAddress.setCity(b.getCreditCardCity());
			billingAddress.setCountryCode("US");
			billingAddress.setLine1(b.getCreditCardStreetAddress1());
			billingAddress.setLine2(b.getCreditCardStreetAddress2());
			billingAddress.setPostalCode(b.getCreditCardZip());
			billingAddress.setState(b.getCreditCardState());

			// ###CreditCard
			// A resource representing a credit card that can be
			// used to fund a payment.
			CreditCard creditCard = new CreditCard();
			creditCard.setBillingAddress(billingAddress);
			creditCard.setCvv2(Integer.parseInt(b.getCreditCardCVV()));
			creditCard.setExpireMonth(Integer.parseInt(b.getCreditCardExpirationMonth()));
			creditCard.setExpireYear(Integer.parseInt(b.getCreditCardExpirationYear()));
			creditCard.setFirstName(b.getCreditCardFirstName());
			creditCard.setLastName(b.getCreditCardLastName());
			creditCard.setNumber(b.getCreditCardNumber());
			creditCard.setType(b.getCreditCardType());

			// ###Details
			// Let's you specify details of a payment amount.
			//Details details = new Details();
			//details.setShipping("1");
			//details.setSubtotal("5");
			//details.setTax("1");

			// ###Amount
			// Let's you specify a payment amount.
			Amount amount = new Amount();
			amount.setCurrency("USD");
			// Total must be equal to sum of shipping, tax and subtotal.
			amount.setTotal(amountToCharge);
			//amount.setDetails(details);

			// ###Transaction
			// A transaction defines the contract of a
			// payment - what is the payment for and who
			// is fulfilling it. Transaction is created with
			// a `Payee` and `Amount` types
			Transaction transaction = new Transaction();
			transaction.setAmount(amount);
			transaction.setDescription("PhoneCall.com");

			// The Payment creation API requires a list of
			// Transaction; add the created `Transaction`
			// to a List
			List<Transaction> transactions = new ArrayList<Transaction>();
			transactions.add(transaction);

			// ###FundingInstrument
			// A resource representing a Payeer's funding instrument.
			// Use a Payer ID (A unique identifier of the payer generated
			// and provided by the facilitator. This is required when
			// creating or using a tokenized funding instrument)
			// and the `CreditCardDetails`
			FundingInstrument fundingInstrument = new FundingInstrument();
			fundingInstrument.setCreditCard(creditCard);

			// The Payment creation API requires a list of
			// FundingInstrument; add the created `FundingInstrument`
			// to a List
			List<FundingInstrument> fundingInstrumentList = new ArrayList<FundingInstrument>();
			fundingInstrumentList.add(fundingInstrument);

			// ###Payer
			// A resource representing a Payer that funds a payment
			// Use the List of `FundingInstrument` and the Payment Method
			// as 'credit_card'
			Payer payer = new Payer();
			payer.setFundingInstruments(fundingInstrumentList);
			payer.setPaymentMethod("credit_card");

			// ###Payment
			// A Payment Resource; create one using
			// the above types and intent as 'sale'
			Payment payment = new Payment();
			payment.setIntent("authorize");
			payment.setPayer(payer);
			payment.setTransactions(transactions);
			

			// ###AccessToken
			// Retrieve the access token from
			// OAuthTokenCredential by passing in
			// ClientID and ClientSecret
			// It is not mandatory to generate Access Token on a per call basis.
			// Typically the access token can be generated once and
			// reused within the expiry window

			// JMJ accessToken = GenerateAccessToken.getAccessToken();

			// ### Api Context
			// Pass in a `ApiContext` object to authenticate
			// the call and to send a unique request id
			// (that ensures idempotency). The SDK generates
			// a request id if you do not pass one explicitly.
			APIContext apiContext = new APIContext(accessToken);
			// Use this variant if you want to pass in a request id
			// that is meaningful in your application, ideally
			// a order id.
			/*
			 * String requestId = Long.toString(System.nanoTime(); APIContext
			 * apiContext = new APIContext(accessToken, requestId ));
			 */

			// Create a payment by posting to the APIService
			// using a valid AccessToken
			// The return object contains the status;
			createdPayment = payment.create(apiContext);

			//LOGGER.info("Created payment with id = " + createdPayment.getId()
			//		+ " and status = " + createdPayment.getState());
			//ResultPrinter.addResult(req, resp, "Payment with Credit Card",
			//		Payment.getLastRequest(), Payment.getLastResponse(), null);
		} catch (PayPalRESTException e) {
			e.printStackTrace();
			//ResultPrinter.addResult(req, resp, "Payment with Credit Card",
			//Payment.getLastRequest(), null, e.getMessage());
		}
		return createdPayment.getState();

	}
```

```
			Billing b = new Billing();
			b.setUser(u);
			b.setCreditCardFirstName("James");
			b.setCreditCardLastName("James");
			b.setCreditCardStreetAddress1("123 Main St");
			b.setCreditCardCity("St Petersburg");
			b.setCreditCardState("FL");
			b.setCreditCardZip("33701");
			b.setCreditCardNumber("4147xxxxxxxxxxxx");
			b.setCreditCardExpirationMonth("12");
			b.setCreditCardExpirationYear("2019");
			b.setCreditCardCVV("186");
			b.setCreditCardType("visa");
			String out = b.processAuthorization("1");
```

Thanks for the help, really need to get this working!

**Comment by pp-randy** [comment]
Can you run a quick test now?

**Comment by pp-randy** [comment]
You shouldn't use a real CC it just needs to pass the luhn algorithm and we have generator on step 4 for that https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413&viewlocale=en_US&direct=en.   

To add to my previous comment, I saw some issues with the card you were using and made some changes and want to see if your error is still occurring.

**Comment by pp-randy** [comment]
@jamesmjones00123 Were you able to test again since my update?

**Comment by jamesmjones00123** [comment]
Hi just got in the office thanks for following up. I am still getting the same error using generated CC number 4125497951815471.

```
response-code: 400	details: name: UNKNOWN_ERROR	message: An unknown error has occurred	details: null	debug-id: 4529ea7a4ba9b	information-link: https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR
	at com.paypal.base.rest.PayPalRESTException.createFromHttpErrorException(PayPalRESTException.java:73)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:441)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:269)
	at com.paypal.api.payments.Payment.create(Payment.java:484)
	at com.serviceproviders.Paypal.processAuthorization(Paypal.java:235)
	at com.objects.Billing.processAuthorization(Billing.java:83)
	at com.test.TestHarness.main(TestHarness.java:34)
Caused by: com.paypal.base.exception.HttpErrorException: Error code : 400 with response : {"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"4529ea7a4ba9b"}
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:174)
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:67)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:427)
	... 5 more
```

**Comment by pp-randy** [comment]
@jamesmjones00123 are you able to provide the request json that is generated? I'm going to try to run it directly against the sandbox and see if I can reproduce.

**Comment by jamesmjones00123** [comment]
The Payment object before I call create method shows: 

```
{
  "intent": "authorize",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [
      {
        "credit_card": {
          "number": "4125497951815471",
          "type": "visa",
          "expire_month": 12,
          "expire_year": 2019,
          "cvv2": 186,
          "first_name": "James",
          "last_name": "James",
          "billing_address": {
            "line1": "242 10th Ave NE",
            "city": "St Petersburg",
            "country_code": "US",
            "postal_code": "33701",
            "state": "FL"
          }
        }
      }
    ]
  },
  "transactions": [
    {
      "transactions": [],
      "amount": {
        "currency": "USD",
        "total": "1"
      },
      "description": "PhoneCall.com"
    }
  ]
}
```

**Comment by pp-randy** [comment]
The JSON is working fine for me.  Created a new sandbox account and I was able to run this as well.  Can you run once more? If its not working now I will escalate internally.

**Comment by jamesmjones00123** [comment]
Still failing with same error...

**Comment by pp-randy** [comment]
I think I see the issue and it appear to be a problem with the business account postal address; this wouldn't happen on live and I apologize it happened in the sandbox. 

Can you generate a new sandbox business account, leaving the default address? Then you would need a new REST App.

**Comment by jamesmjones00123** [comment]
I created a new sandbox business account, and a new REST app. 

But I do not understand the relevance of the business account postal address. I do not see any sort of address specified in the Profile of either a Business or Profile test account.

So what address should I be using to do a test transaction, if I do not see any default address?

**Comment by pp-randy** [comment]
Its the address associated to the business account, it was blank, and I encountered issues adding the default one. Is the new account working?

**Comment by jamesmjones00123** [comment]
Let's take a step back here, I think I am missing something fundamental.

1. I create a an App with Client ID and Secret. I add that to the paypal.properties file.

2. I want to test an 'authorize' transaction via the code posted. I use the visa card associated with one of my Personal Test Accounts. The Test Accounts do not have fields to specify a billing address when I create them. What valid billing address will the system accept?

```
			Address billingAddress = new Address();
			billingAddress.setCity(b.getCreditCardCity());
			billingAddress.setCountryCode("US");
			billingAddress.setLine1(b.getCreditCardStreetAddress1());
			billingAddress.setLine2(b.getCreditCardStreetAddress2());
			billingAddress.setPostalCode(b.getCreditCardZip());
			billingAddress.setState(b.getCreditCardState());

```

3. I don't understand what the Business Test Account has to do with the Java code. Does this enter into the authorization process at all? I thought the Business Test Account was used to view the transactions in the sandbox at sandbox.paypal.com?

**Comment by pp-randy** [comment]
I apologize for the confusion; this wasn't a code issue.  It was a problem with the business sandbox account missing its address, which is why I asked you to create a new one. The account the rest app is tied to doesn't appear to be set up right, so I think the sandbox account creator tool must have had an issue when your original sandbox test business account was created.  

The Business Test Account is used to log into to see transactions, but its configuration is important as well.  Nothing here seem to be wrong with your side, it appears it was a PayPal sandbox issue.

**Comment by pp-randy** [comment]
I am looking over your accounts and see the -facilitator is the only one with a REST app tied to it.  Don't use your current -facilitator account its the account that doesn't appear to have been created by the sandbox tool correctly.

**Comment by jamesmjones00123** [comment]
Ok. For the purposes of this app I am only interested in direct credit card transactions, so I don't think I even need to use any of the end user sandbox accounts. 

I updated my config to use my new app, E2C, but I am still getting the same error when I try to authorize the credit card. I CAN save the credit card @ Paypal, however.

**Comment by pp-randy** [comment]
That's because its associated to the -facilitator business.  You need to generate a new sandbox business account and the app needs to point to it.  

When you are here: https://developer.paypal.com/developer/applications/create
You need to select a different account in this drop down for Sandbox Developer Account
![image](https://cloud.githubusercontent.com/assets/6819909/16312727/af2f3e18-393b-11e6-90d9-c1bcae66049f.png)

**Comment by pp-randy** [comment]
If you still have issues getting this sorted. Create a ticket here: http://www.paypal-techsupport.com/app/ask and respond back with just the ticket number.  We can do a call and screen share to get this sorted out if needed.

**Comment by jamesmjones00123** [comment]
Eureka! That worked. I did not understand the relationship between the app and the dev account but I do now. Thanks!
