### ISSUE TITLE
Error with 1.9.3 Creating Sale

### ISSUE THREAD

**Issue by prowave** [paypal/PayPal-Java-SDK#243]
### General Information

- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used: 1.8
- SDK Version: 1.9.3

### Issue Description

All Payment attempts end with :

```
(was java.lang.NullPointerException) (through reference chain: com.paypal.api.payments.Sale["clientCredential"])
```

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by prowave** [comment]
Here is the stack trace.  The NPE occurs when the default configuration file is not present, which we do not use.

```
Caused by: java.lang.NullPointerException: null
	at com.paypal.base.rest.PayPalResource.getConfigFileProperties(PayPalResource.java:525) ~[rest-api-sdk-1.9.3.jar:na]
	at com.paypal.base.rest.PayPalResource.getCredential(PayPalResource.java:498) ~[rest-api-sdk-1.9.3.jar:na]
	at com.paypal.base.rest.PayPalResource.getClientCredential(PayPalResource.java:513) ~[rest-api-sdk-1.9.3.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:633) ~[jackson-databind-2.7.4.jar:2.7.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678) ~[jackson-databind-2.7.4.jar:2.7.4]
```

**Comment by prowave** [comment]
I think we found the issue in PayPalReource.

```
	public static ClientCredentials getCredential() {
		ClientCredentials credentials = new ClientCredentials();
		Properties configFileProperties = getConfigFileProperties();
		addConfigurations(configFileProperties);
		credentials.setClientID(configurationMap.get(Constants.CLIENT_ID));
		credentials.setClientSecret(configurationMap.get(Constants.CLIENT_SECRET));
		return credentials;
	}
```

Before calling getConfigFIleProperties(), which is causing the NPW for us b/c it isnt a resource available, check to see if `configInitialized` is true or not.

We call this to setup our credentials

```
PayPalResource.initConfig(configProperties);
```
Which sets `configInitialized = true;`

Just repect that the confi is already initialized and dont try to read the sdk_config.properties every time. :)  HTH

Thanks, and looking forward to testing 1.9.4!

**Comment by prowave** [comment]
Disregard this please.  The error comes when trying to serialize the object using Jackson's ObjectMapper.  While that may be an issue you want to explore, its not a bug or issue for me as I found your toJSON() methods that use GSON for the same thing.
