### ISSUE TITLE
NullPointerException at ApiContext call

### ISSUE THREAD

**Issue by karanvs** [paypal/PayPal-Java-SDK#245]
### General Information

- Mode (Sandbox/Live):Sanbox
- PayPal-Debug-ID(s) (from any logs):  not getting any such id
- Version of Java used: 7
- SDK Version: I am using following dependency in my code, compile 'com.paypal.sdk:rest-api-sdk:+',
I am using this in Android.

### Issue Description

Getting NullPointerException at the call:

  APIContext context = new APIContext(clientId, clientSecret, "sandbox");

here is my log details:

 Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                                                       at org.apache.logging.log4j.util.ReflectionUtil$PrivateSecurityManager.getCallerClass(ReflectionUtil.java:301)
                                                                                       at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:214)
                                                                                       at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
                                                                                       at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
                                                                                       at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
                                                                                       at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
                                                                                       at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
                                                                                       at com.paypal.base.rest.OAuthTokenCredential.<clinit>(OAuthTokenCredential.java:36)
                                                                                       at com.paypal.base.rest.APIContext.<init>(APIContext.java:78) 
                                                                                       at com.paypal.base.rest.APIContext.<init>(APIContext.java:66) 

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by jaypatel512** [comment]
From the looks of it, it feels like you are missing logging dependency. 

Can you add below dependencies or other logger adapter as per your project configuration:

```gradle
    dependencies {
        compile 'log4j:log4j:1.2.14'
        compile 'org.apache.logging.log4j:log4j-api:2.1'
        compile 'org.apache.logging.log4j:log4j-core:2.1'
    }
```

**Comment by jaypatel512** [comment]
Please re-open if this does not fix the issue.
