### ISSUE TITLE
INVALID_TOKEN during billing agreement execute

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-Java-SDK#291]
Following up on https://github.com/paypal/PayPal-REST-API-issues/issues/19#issuecomment-299093188

-------------
Do we any have update regarding this issue, I am using PayPal-Java-SDK and i am able to create agreement but its giving me id as null, when i try to execute the agreement it is giving me below error.
response-code: 400	details: name: INVALID_TOKEN	message: Token is invalid.

I guess when i try to execute that the state of agreement is not ACTIVE, in order to make it active by patch i need agreement ID which i am getting as null.

Let me know if there is any other way to execute the agreement.
Thanks in advance

-----------
@pp-randy I am using following code 

Payer payer = new Payer();
payer.setPaymentMethod("paypal");
Plan plan1 = new Plan();
plan1.setId(plan.getId()); // plan id of plan created
Agreement agreement= new Agreement("Standard Membership", "Food of the World Club Standard Membership", "2017-06-03T09:13:49Z", payer, plan1);
agreement.setState("ACTIVE"); // to just check even though if i dont keep i get same error
Agreement createAgreement= agreement.create(context);
Agreement activeAgreement = Agreement.execute(context, createAgreement.getToken());

**In the logs i am getting this :** 
[ERROR] com.paypal.base.HttpConnection - Response code: 400	Error response: {"name":"INVALID_TOKEN","message":"Token is invalid.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_TOKEN","debug_id":"a73c3ff6c6f27"}
response-code: 400	details: name: INVALID_TOKEN	message: Token is invalid.	details: null	debug-id: a73c3ff6c6f27	information-link: https://developer.paypal.com/webapps/developer/docs/api/#INVALID_TOKEN
	at com.paypal.base.rest.PayPalRESTException.createFromHttpErrorException(PayPalRESTException.java:72)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:431)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:295)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:228)
	at com.paypal.api.payments.Agreement.execute(Agreement.java:202)
	at com.js.agtools.controller.SubscriptionSample.main(SubscriptionSample.java:164)
Caused by: com.paypal.base.exception.HttpErrorException: Response code: 400	Error response: {"name":"INVALID_TOKEN","message":"Token is invalid.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_TOKEN","debug_id":"a73c3ff6c6f27"}
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:162)
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:65)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:417)
	... 4 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-0EL033744E495632J/agreement-execute
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:132)
	... 6 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-0EL033744E495632J/agreement-execute
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:117)
	... 6 more

Please let me know if i am missing any thing
Thanks In Advance

---------------

**Comment by pp-randy** [comment]
@pathaalok once you create an agreement, you need to redirect the payer to PayPal using the approval URL.  

Are you doing create then execute immediately?  
```
Agreement createAgreement= agreement.create(context);
Agreement activeAgreement = Agreement.execute(context, createAgreement.getToken());
```
If so, you should use the approval_url to redirect the payer to PayPal first.  When they return to your site with approval then you would execute.  

I don't see sample code for the agreement portion, so flagging this as an sdk-enhancement and will follow up on that further. 

However, you should be able to get the approval URL similarly like how it is done for a payment [payments/servlet/PaymentWithPayPalServlet.java#L166-L173](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/payments/servlet/PaymentWithPayPalServlet.java#L166-L173).

**Comment by pathaalok** [comment]
@pp-randy 

When you say approval URL, is it the PAYPAL authorization URL where the user has to login with his credential?

**Comment by pp-randy** [comment]
Yes that is what I mean

**Comment by pp-randy** [comment]
@pathaalok were you able to execute after using the approval url?

**Comment by pathaalok** [comment]
@pp-randy 

I am getting the redirect link from create agreement response, if i redirect it to the approval URL can you say me what are the next things should be done. If possible can you send sample code in Java after create agreement (How to handle once user gets authenticated and after payment success)

**Comment by pp-randy** [comment]
I am following up further on sample code, since it is not in the SDK for this product. 

Once the buyer returns from the approval URL that is when you would execute the agreement.
`Agreement.execute(context, token);`
The token is returned to your site as a query parameter in the URL when the buyer is redirected back from PayPal.

**Comment by pathaalok** [comment]
@pp-randy i am using Single Page Application, How can i redirect the user to the approval link(i am getting it from create agreement) and how should  i handle once user returns from paypal.

Can you please let me know the steps, which could be great help

Thanks in Advance

**Comment by pathaalok** [comment]
@pp-randy I am able to execute the agreement, with the above steps u specified thank you.

What is the process to test for subcription,Can you refer me any link?

**Comment by pp-randy** [comment]
@pathaalok can you give me a debug_id from your execute and I will look things over for you.  For sandbox testing I usually use daily billing plans so I can get results more quickly.  Since you are using a single page app this post using Checkout JS might interest you and maybe require minimal changes https://github.com/paypal/PayPal-node-SDK/issues/261#issuecomment-295308859.

**Comment by pathaalok** [comment]
@pp-randy 

I tested it and its working all good, thanks for guidance.

One thing i wanted to know, 
If an user has subscribed for monthly subscription and if he does not have enough amount in his paypal account for the second month, How paypal will be handling it and how can i as develop need to handle.

This is the only scenario i am left with. Please let me know how can we handle this.

Thanks in Advance.

**Comment by pp-randy** [comment]
@pathaalok you will want to use Instant Payment Notification.  
We are tracking an enhancement to add a webhook for these denied payments. 
More details here: https://github.com/paypal/PayPal-REST-API-issues/issues/15

**Comment by pathaalok** [comment]
@pp-randy So as of now we don't have that feature,until that is closed right??

**Comment by pp-randy** [comment]
For Webhooks that is the case, but Instant Payment Notification should work for you.

**Comment by pp-randy** [comment]
Since your initial issue is resolved I am closing this issue; however, let me know if you have additional questions.

**Comment by pathaalok** [comment]
@pp-randy Can you please provide any reference for java implementation for IPN for subcription type paymetns

**Comment by pp-randy** [comment]
There is some information setting up a listener for Java in our Merchant SDK https://github.com/paypal/merchant-sdk-java/blob/master/merchantsample/IPN-README.md

IPNs will be sent for many things, what you want to look for with this use case is `txn_type= recurring_payment_failed` in IPN request data.

**Comment by selected-pixel-jameson** [comment]
@pp-randy I know that this is completely unrelated, but I'm having issues with my sandbox users and can't get logged in to their sandbox.paypal.com accounts. https://stackoverflow.com/questions/44438671/unable-to-process-your-request-error-after-logging-into-sandbox-paypal-com

**Comment by xiaoleih41** [comment]
I just tried to log in from the site and phone, I don't have any issue. If the issue persistent. please file a ticket https://www.paypal-techsupport.com/, please provide the specific **time stamp** and `correlationId` if you can get it from the source code of that page.  I am locking the conversation as the original topic was closed on this thread
