### ISSUE TITLE
REST API - Read Timeout

### ISSUE THREAD

**Issue by shivajid** [paypal/PayPal-Java-SDK#316]
### General information

* SDK/Library version:  Latest
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Java 1.8

### Issue description

We have written a small sample code for REST API call. We activated an account and are trying to test it,

Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:147)

**Comment by NBussa** [comment]
We are having same issue.  How to fix this error?
`
![image](https://user-images.githubusercontent.com/19960960/30233819-e6ff9fb8-94ac-11e7-84d7-6d34c44d205c.png)
`

**Comment by xiaoleih41** [comment]
Please provide the `DebugId `associated with the call and the type of call you are trying to make for us to reproduce the error.

**Comment by xiaoleih41** [comment]
Close this due to inactivity. Please resubmit when you provide additional information.
