### ISSUE TITLE
Sample call com.paypal.api.sample.ValidateCert fails with 400 error

### ISSUE THREAD

**Issue by NickKononovich** [paypal/PayPal-Java-SDK#380]
### General information

* SDK/Library version: 1.14.0
* Environment: sandbox
* `PayPal-Debug-ID` values: no
* Language, language version, and OS: java 1.8.0_201

### Issue description
com.paypal.api.sample.ValidateCert#main is failing 
response-code: 0	details: null
	at com.paypal.base.SSLUtil.downloadCertificateFromPath(SSLUtil.java:265)
	at com.paypal.api.payments.Event.validateReceivedEvent(Event.java:205)
	at com.paypal.api.sample.ValidateCert.main(ValidateCert.java:35)
Caused by: com.paypal.base.exception.HttpErrorException: Response code: 400	Error response: Server returned HTTP response code: 400 for URL: https://api.sandbox.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-a5cafa77
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:162)
	at com.paypal.base.SSLUtil.downloadCertificateFromPath(SSLUtil.java:263)
	... 2 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.sandbox.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-a5cafa77
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:132)
	... 3 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.sandbox.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-a5cafa77
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:117)
	... 3 more

**Comment by prakash-gangadharan** [comment]
PR Raised : https://github.com/paypal/PayPal-Java-SDK/pull/393
