### ISSUE TITLE
Only in some cases this error is happening: VALIDATION_ERROR Invalid request - see details	field: redirect_urls.return_url

### ISSUE THREAD

**Issue by Bazarov47** [paypal/PayPal-Java-SDK#384]
SDK/Library version: 1.14.0
Environment: Production
`PayPal-Debug-ID`: c5a32fc1ee12c
Language, language version, and OS: Java 1.8.0_131 on Google Cloud

### Issue description

Exception = response-code: 400	details: name: VALIDATION_ERROR	message: Invalid request - see details	details: [{
  "field": "redirect_urls.return_url",
  "issue": "{Url}"
}]	debug-id: c5a32fc1ee12c	information-link: https://developer.paypal.com/docs/api/payments/#errors
	at com.paypal.base.rest.PayPalRESTException.createFromHttpErrorException(PayPalRESTException.java:72)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:431)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:295)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:228)
	at com.paypal.api.payments.Payment.create(Payment.java:149)
Caused by: com.paypal.base.exception.HttpErrorException: Response code: 400	Error response: {"name":"VALIDATION_ERROR","details":[{"field":"redirect_urls.return_url","issue":"{Url}"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"c5a32fc1ee12c"}
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:162)
	at com.paypal.base.GoogleAppEngineHttpConnection.executeWithStream(GoogleAppEngineHttpConnection.java:87)
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:65)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:417)
	... 66 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.paypal.com/v1/payments/payment
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:132)
	... 69 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.paypal.com/v1/payments/payment

**Comment by prakash-gangadharan** [comment]
@Bazarov47 , do you still facing this issue consistently and if yes can you share here the latest PayPal-Debug-ID ?

**Comment by prakash-gangadharan** [comment]
Hi @Bazarov47 , am closing this issue now. Please reopen with latest instance if you still see this issue around.

Thanks!
