### ISSUE TITLE
Verifying Payment

### ISSUE THREAD

**Issue by MoltenDM** [paypal/PayPal-Java-SDK#58]
i am trying to verify a paypal payment by using 
Payment payment = Payment.get(accessToken, paymentID);

but i get a connection reset error could you please help me fix this problem

**Comment by MoltenDM** [comment]
@jaypatel512 
i ran the code you gave me and i get the exception "retry fails..  check log for more information"
here is the code i tried.
Map<String, String> sdkConfig = new HashMap<>();
sdkConfig.put("mode", "sandbox");
accessToken = new OAuthTokenCredential(clientID,
clientSecret, sdkConfig).getAccessToken();
//up to this point it works fine. i receive the access token
APIContext apiContext = new APIContext(accessToken);
Payment payment = new Payment();
Payment createdPayment = payment.create(apiContext);

//according to your code i noticed you have a variable payment
Payment createdPayment = payment.create(apiContext);
where is the declaration for that variable i just did this:
Payment payment = new Payment();
not sure if that is correct.

**Comment by jaypatel512** [comment]
Is it possible for you to checkout the logs ? I think the issue seems to be related with SSLv3. It may be a long shot, but the message you are getting "retry fails", is only done when we try to make connection to PayPal from the SDK, and are not getting proper certificate verification to prevent hacking, and it is not finding the proper cert. I may be wrong.

Btw, It would be certainly very helpful if you could run our samples that are provided in the sdk. Can you please check if those are going through fine. If those are failing, we would know there is some issue other than your code. Probably some configurations, or environment settings, or probably bug in SDK. 

Thanks @MoltenDM

**Comment by dahawkish** [comment]
Hi Jaypatel51,

SSLv3? Do you think it will be a problem related to Tomcat or RESTful services? I will send you the log. Do you have an email I can reach you? I am sending from android@goldendata.org.

Team with @MoltenDM

**Comment by MoltenDM** [comment]
@jaypatel512 
i ran the samples and i got the same issues.
i have noticed that the sample gives the same issue on GenerateAccessToken

which i fixed by changing it to the following code

Map<String, String> sdkConfig = new HashMap<>();
sdkConfig.put("mode", "sandbox");
accessToken = new OAuthTokenCredential(clientID,
                    clientSecret, sdkConfig).getAccessToken();
this fixes the GenerateAccessToken problem but not the Payment verification.

**Comment by MoltenDM** [comment]
this is the log file.
09-Jan-2015 19:38:20.020 INFO [http-nio-9999-exec-9] null.null Registering the Jersey servlet application, named golden.data.webservices.ApplicationConfig, at the servlet mapping /webresources/*, with the Application class of the same name.
09-Jan-2015 19:38:20.478 INFO [http-nio-9999-exec-9] null.null Initiating Jersey application, version Jersey: 2.5.1 2014-01-02 13:43:00...
09-Jan-2015 19:38:37.218 SEVERE [http-nio-9999-exec-2] null.null Caught exception while handling error response
 java.net.SocketException: Connection reset
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1888)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1883)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1882)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1455)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.paypal.core.HttpConnection.execute(HttpConnection.java:109)
	at com.paypal.core.rest.OAuthTokenCredential.generateOAuthToken(OAuthTokenCredential.java:210)
	at com.paypal.core.rest.OAuthTokenCredential.generateAccessToken(OAuthTokenCredential.java:164)
	at com.paypal.core.rest.OAuthTokenCredential.getAccessToken(OAuthTokenCredential.java:132)
	at golden.data.old.GetPaymentServlet.doPost(GetPaymentServlet.java:119)
	at golden.data.old.GetPaymentServlet.doGet(GetPaymentServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:911)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:703)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:674)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1534)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.paypal.core.HttpConnection.execute(HttpConnection.java:91)
	... 29 more

**Comment by dahawkish** [comment]
It looks like the problem is really on Tomcat. 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)

**Comment by jaypatel512** [comment]
Thanks @MoltenDM , @dahawkish I see it is trying to create a new instance of HttpURLConnection, and failing there. When I use eclipse, and run our samples using jetty plugin, it works fine. Let me see if I could war this up and host it on tomcat, and see if there is any difference.

Generally, you get `connection reset` if you are using an httpconnection from the pool that is already closed/stale. If it was server, it would give you `connection reset by peer`. 

Btw, issues like this are easily debugged if reproduced on local machine. are you guys having this issue on your local machine ? or your production server ?

**Comment by MoltenDM** [comment]
@jaypatel512 this issue is on my local machine. and i am using netbeans.
but i noticed that i do receive an access token using 
Map sdkConfig = new HashMap<>();
sdkConfig.put("mode", "sandbox");
accessToken = new OAuthTokenCredential(clientID,
clientSecret, sdkConfig).getAccessToken();
without the first two lines it does not work (like the sample).

**Comment by jaypatel512** [comment]
This is how I created a new servlet in our sample-app project

src/main/java/com/paypal/api/payments/servlet/SampleServlet.java

```java
// #GetPayment Sample
// This sample code demonstrates how you can retrieve
// the details of a payment resource.
// API used: /v1/payments/payment/{payment-id}
package com.paypal.api.payments.servlet;

import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import com.paypal.api.payments.Payment;
import com.paypal.api.payments.util.GenerateAccessToken;
import com.paypal.base.rest.APIContext;
import com.paypal.base.rest.OAuthTokenCredential;
import com.paypal.base.rest.PayPalRESTException;
import com.paypal.base.rest.PayPalResource;

/**
 * @author lvairamani
 * 
 */
public class SampleServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;
	private static final Logger LOGGER = Logger
			.getLogger(SampleServlet.class);

	public void init(ServletConfig servletConfig) throws ServletException {
		

	}

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		doPost(req, resp);

	}

	// ##GetPayment
	// Call the method with a valid Payment ID
	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		try {
			Map<String, String> sdkConfig = new HashMap<String, String>();
			sdkConfig.put("mode", "sandbox");
			String accessToken = new OAuthTokenCredential("EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM",
					"EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM",
					sdkConfig
					).getAccessToken();
			//up to this point it works fine. i receive the access token
			APIContext apiContext = new APIContext(accessToken);
			Payment payment = Payment.get(apiContext, "PAY-0XL713371A312273YKE2GCNI");
					

			
			LOGGER.info("Payment retrieved ID = " + payment.getId()
					+ ", status = " + payment.getState());
			req.setAttribute("response", Payment.getLastResponse());
		} catch (PayPalRESTException e) {
			req.setAttribute("error", e.getMessage());
		}
		req.getRequestDispatcher("response.jsp").forward(req, resp);
	}

}

```

added these lines to web.xml
```xml

<servlet>
		<servlet-name>SampleServlet</servlet-name>
		<servlet-class>com.paypal.api.payments.servlet.SampleServlet</servlet-class>
	</servlet>
.....
<servlet-mapping>
		<servlet-name>SampleServlet</servlet-name>
		<url-pattern>/sample</url-pattern>
	</servlet-mapping>
```

This is what will do a get on your payments.

Also, can you please try to run our sample project using maven jetty plugin. All you have to do is, to go to rest-api-sample directory, and run `mvn jetty:run`. Most likely, it would show something like this:
```
[INFO] Webapp directory = /Users/japatel/Documents/workspace/java/PayPal-Java-SDK/rest-api-sample/src/main/webapp
[INFO] Starting jetty 6.1.26 ...
[INFO] jetty-6.1.26
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
[INFO] Started SelectChannelConnector@0.0.0.0:9091
[INFO] Started Jetty Server
```

Open localhost:9091/rest-api-sample/ and you should be able to click on any samples. Let me know if those ones go through your local machine or not. And if not, we could work together and see what the issue is over hangout or a chat outside github. Let me know

**Comment by dahawkish** [comment]
Thanks you so much. Will do. I think the Resful API does not work given by Paypal sometimes. I noticed it might be the other version of HTML.
Ning

**Comment by dahawkish** [comment]
Jay,
We used tomcat as an application server, and azure is the end server. 

Ning

**Comment by dahawkish** [comment]
Hi Jay, 
After a discussion with @MoltenDM. We already have this servlet, and we are not using jetty.
The problem is with the HTTP connection. 
I think I will try this 
https://github.com/paypal/sdk-core-java/blob/master/src/main/java/com/paypal/core/HttpConnection.java

Will let you know. Faris will invite you for a call if you have time.

Thanks,
Ning

**Comment by juwlee** [comment]
@dahawkish @MoltenDM I wonder what version of this SDK you are using, but can you please try the latest version and see if the issue persists? It would be probably worth trying jetty and the code samples as well.

**Comment by dahawkish** [comment]
Hi Jay,
We have issues on the HTTP connection. I think here are my steps to approach the problem or I will send you a copy of the RESTful.
1. I will use the updated SDK2. If it is not working, I will make a request to have a call. 
3. I think the problem is the application server, but I am not very sure. 

I will leave the rest to Faris to contact you.
Thanks,Ning
      
   
@dahawkish @MoltenDM I wonder what version of this SDK you are using, but can you please try the latest version and see if the issue persists? It would be probably worth trying jetty and the code samples as well.—

**Comment by MoltenDM** [comment]
@jaypatel512 i fixed the problem, thanks for your help

**Comment by jaypatel512** [comment]
Hey MoltenDM, I am glad you were able to get it to work. BTW, would you mind sharing the solution if it could help more devs out here !

Thanks

**Comment by MoltenDM** [comment]
i believe the problem was with the "sdk_config.properties".
i just deleted that from my project and added apiContext.setConfigurationMap(sdkConfig);
the code is bellow.

Map<String, String> sdkConfig = new HashMap<>();
 sdkConfig.put("mode", "sandbox");

accessToken = new OAuthTokenCredential(clientID,clientSecret, sdkConfig).getAccessToken();
APIContext apiContext = new APIContext(accessToken);
apiContext.setConfigurationMap(sdkConfig);
