### ISSUE TITLE
retry fails.. check log for more information

### ISSUE THREAD

**Issue by ankur99999** [paypal/PayPal-Java-SDK#75]
When ever i try to pay with credit card in your sample, I got this error:-

retry fails.. check log for more information

Can you please tell me what's the problem?

**Comment by juwlee** [comment]
@ankur99999 what nested error(s) do you see? Can you try curl? It will tell whether it is a server-side issue or an SDK issue.

**Comment by ankur99999** [comment]
Here is error log of my catline

10:52:19.342 [http-bio-8080-exec-3] ERROR com.paypal.base.HttpConnection - Caught exception while handling error response
java.net.SocketTimeoutException: Read timed out
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.6.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.6.0_31]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.6.0_31]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:534) ~[?:1.6.0_31]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1458) ~[?:1.6.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1452) ~[?:1.6.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1106) ~[?:1.6.0_31]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:397) ~[?:1.6.0_31]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[?:1.6.0_31]
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:113) [rest-api-sdk-1.1.0.jar:?]
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:402) [rest-api-sdk-1.1.0.jar:?]
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:260) [rest-api-sdk-1.1.0.jar:?]
	at com.paypal.api.payments.Payment.create(Payment.java:358) [rest-api-sdk-1.1.0.jar:?]
	at com.paypal.api.payments.servlet.PaymentWithCreditCardServlet.doPost(PaymentWithCreditCardServlet.java:184) [PaymentWithCreditCardServlet.class:?]
	at com.paypal.api.payments.servlet.PaymentWithCreditCardServlet.doGet(PaymentWithCreditCardServlet.java:62) [PaymentWithCreditCardServlet.class:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668) [servlet3.0-jsp2.2-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770) [servlet3.0-jsp2.2-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.57]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.57]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.57]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503) [catalina.jar:7.0.57]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.57]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.57]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.57]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.57]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [catalina.jar:7.0.57]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) [tomcat-coyote.jar:7.0.57]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.57]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-coyote.jar:7.0.57]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146) [?:1.6.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.6.0_31]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.57]
	at java.lang.Thread.run(Thread.java:701) [?:1.6.0_31]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.6.0_31]
	at java.net.SocketInputStream.read(SocketInputStream.java:146) ~[?:1.6.0_31]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442) ~[?:1.6.0_31]
	at sun.security.ssl.InputRecord.read(InputRecord.java:480) ~[?:1.6.0_31]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:883) ~[?:1.6.0_31]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:840) ~[?:1.6.0_31]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:94) ~[?:1.6.0_31]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235) ~[?:1.6.0_31]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275) ~[?:1.6.0_31]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334) ~[?:1.6.0_31]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:688) ~[?:1.6.0_31]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633) ~[?:1.6.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1162) ~[?:1.6.0_31]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:397) ~[?:1.6.0_31]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[?:1.6.0_31]
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:96) ~[rest-api-sdk-1.1.0.jar:?]
	... 24 more
10:52:19.372 [http-bio-8080-exec-3] ERROR com.paypal.base.HttpConnection -  Retry  No : 1...

**Comment by mpateiru** [comment]
@ankur99999 Have you checked proxy settings in your sdk_config.properties and proxy settings of browser if these are correctly set. Since it seems to be http connection timeout error, it is mostly related to proxy settings. Confirm these settings once again.

**Comment by ankur99999** [comment]
yes, I checked that. My proxy setting are

http.ProxyPort=8080
http.ProxyHost=127.0.0.1
http.UseProxy=false
http.ProxyUserName=null
http.ProxyPassword=null

And may be its correct.

**Comment by mpateiru** [comment]
Do you have any proxy settings for your browser to access internet? If no, then you need to comment out above properties.

#http.ProxyPort=8080
#http.ProxyHost=127.0.0.1
#http.UseProxy=false
#http.ProxyUserName=null
#http.ProxyPassword=null 

this should solve your problem.

**Comment by ankur99999** [comment]
I did, As you said, But again getting same error:-
     retry fails.. check log for more information

12:08:05.700 [http-bio-8080-exec-2] ERROR com.paypal.base.HttpConnection - Caught exception while handling error response
java.net.SocketTimeoutException: Read timed out

**Comment by ankur99999** [comment]
@mpateiru  Here is my complete sdk_config.properties file:

# Connection Information
http.ConnectionTimeOut=5000
http.Retry=1
http.ReadTimeOut=30000
http.MaxConnection=100

# HTTP Proxy configuration
# If you are using proxy set http.UseProxy to true and replace the following values with your proxy parameters
#http.ProxyPort=8080
#http.ProxyHost=127.0.0.1
#http.UseProxy=false
#http.ProxyUserName=null
#http.ProxyPassword=null

#Set this property to true if you are using the PayPal SDK within a Google App Engine java app
http.GoogleAppEngine = false

# Service Configuration
service.EndPoint=https://api.sandbox.paypal.com
# Live EndPoint
#service.EndPoint=https://api.paypal.com

# Credentials
clientId=AVAR9sU7-PeAkod_K-OfpwQDWfqJBiy2kKvlVALRZNmgFDLpIP4fRobQtJJFULzDGZJV0RaXKsIlBhXc
clientSecret=EMl1mhn8bgavgHDkjfDdWWm_u59HCeD2w3v4IDHKuuWWc6hH5bCnB5po9X3kMrRLEzht41asrJx7clnK


But again fails.

**Comment by ankur99999** [comment]
Peoples are getting this error since long time. Here is some stackoverflow questions.

http://stackoverflow.com/questions/26414403/is-the-paypal-developer-sandbox-environment-down-again

http://stackoverflow.com/questions/28291729/retry-fails-check-log-for-more-information-paypal

**Comment by mpateiru** [comment]
properties file looks fine to me. May be you should once try what Juwlee is saying above, that should give more insight on issue.

**Comment by ankur99999** [comment]
I don't know how to check this with curl, Is there any guide for that?

**Comment by avidas** [comment]
@ankur99999 have a look at https://developer.paypal.com/docs/integration/direct/make-your-first-call/ to see how to get access token, and make api call via curl. Mac/Linux terminals come with curl installed, you may need to install curl if on windows.

**Comment by juwlee** [comment]
@ankur99999 I have reproduced the issue with SDK samples. Digging deeper, I have found out that it was caused by an internal error. An internal ticket (PPTIPS-2511) has been opened to track this issue. I will circle back to you when there is an update.

Along with that, it would be great to try out curl as documented on the above link that @avidas provided. It will tell API bugs from SDK ones.

**Comment by jspiewak** [comment]
I was receiving the same error. I increased the read timeout to 60 seconds, and get a 500 response instead. My debug id is 0d9e33d069693. Can you say whether or not that is the same error tracked in PPTIPS-2511? If so, is there an ETA for a fix?

**Comment by jaypatel512** [comment]
One of the reason why the samples are failing is because of the credit card number used in the sample. We recently realized that because that credit card is used in samples, and tested with hundreds of transactions from different account, it is causing it to delays in retrieving that information, as it is an anomaly from usual credit card used in PayPal. 

To resolve that issue, you could use the credit card provided in your developer account as shown below:
https://developer.paypal.com/webapps/developer/applications/accounts
![screen shot 2015-02-09 at 11 55 26 am](https://cloud.githubusercontent.com/assets/1309895/6111988/933bb6d2-b052-11e4-8662-9c4c85d00051.png)

Using a specific credit card that your sandbox account would have would make your samples working fine with Credit Cards. 

We are trying to find a better solution than this, but in the mean time, please try this, and see if it resolves the issue.

**Comment by jspiewak** [comment]
Yes, it was definitely that I was using a test credit card from another system.
However, taking over 30 seconds to return a 500 server error for a bad credit card in a credit card processing system seems pretty outrageous.

**Comment by ankur99999** [comment]
Yes, I also tried with different client secret and id, And with another credit card( tried with both your and my app credit card) But still not working.

**Comment by jziaja** [comment]
@jspiewak, PayPal is actively working on fixing the experience on sandbox for overused credit cards.  Unfortunately, there's no ETA on when this fix will go into effect, but rest assured they are working on it.  Our team (the SDK team) has been keeping up with the team responsible to forward them any and all developer feedback regarding the current state of the system.  We completely agree with you that the current lag on sandbox followed by a very unhelpful 500 is absolutely unacceptable.

@ankur99999, it would help us out if you could share what the request looks like that is being sent, along with the full response you're receiving.  That way we can determine if your issue is the same 500 error related to processing overused credit cards on sandbox or something else completely.  As always, if the response contains a `debug_id`, that would help our team greatly as we can then look into the logs to see what specifically caused the problem.

Were you able to get the cURL calls working?  If so, could you share the exact calls you're making using cURL?

**Comment by mattjacunski** [comment]
Just FYI - PayPal has been “working on” the sandbox cc issue for maybe 2 years now…

On Feb 10, 2015, at 7:54 AM, Jason Ziaja <notifications@github.com<mailto:notifications@github.com>> wrote:


@jspiewak<https://github.com/jspiewak>, PayPal is actively working on fixing the experience on sandbox for overused credit cards. Unfortunately, there's no ETA on when this fix will go into effect, but rest assured they are working on it. Our team (the SDK team) has been keeping up with the team responsible to forward them any and all developer feedback regarding the current state of the system. We completely agree with you that the current lag on sandbox followed by a very unhelpful 500 is absolutely unacceptable.

@ankur99999<https://github.com/ankur99999>, it would help us out if you could share what the request looks like that is being sent, along with the full response you're receiving. That way we can determine if your issue is the same 500 error related to processing overused credit cards on sandbox or something else completely. As always, if the response contains a debug_id, that would help our team greatly as we can then look into the logs to see what specifically caused the problem.

Were you able to get the cURL calls working? If so, could you share the exact calls you're making using cURL?

**Comment by sultanshakir** [comment]
@jaypatel512 Using the card number in my Sandbox test account worked!  Thank you.

**Comment by juwlee** [comment]
Glad to hear the issue was resolved @ankur99999 .

**Comment by stryd3r** [comment]
Hello,
Unfortunately I have also this problem when I'm trying to make a payment with PaymentWithCreditCardServlet.  When payment.create(apiContext); is called I got an PayPalRESTException and the cause is "com.paypal.base.exception.HttpErrorException: retry fails..  check log for more information".  Also the responsecode is 0. Can you please help me with this?
Thank you!

**Comment by sultanshakir** [comment]
@stryd3r did you try changing the information in the GetAuthorizationServlet.java file [here](https://github.com/paypal/PayPal-Java-SDK/blob/23a245bf5722a3d28bd663d35858e1e0cd4fdc81/rest-api-sample/src/main/java/com/paypal/api/payments/servlet/GetAuthorizationServlet.java#L164) ?

**Comment by stryd3r** [comment]
@sultanshakir  I set also there the necessary information but still I have the same error. Moreover, when I try to test "Payments using credit card information" method doPost from GetAuthorizationServlet is not used, therefore I think only 

		CreditCard creditCard = new CreditCard();
		creditCard.setBillingAddress(billingAddress);
		creditCard.setCvv2(111);
		creditCard.setExpireMonth(05);
		creditCard.setExpireYear(2021);
		creditCard.setFirstName("Adrian");
		creditCard.setLastName("Barna");
		creditCard.setNumber("4032037506926423");
		creditCard.setType("visa");

from PaymentWithCreditCardServlet is important. Can be this related to the fact that on developer.paypal.com I didn't found the Cvv2 for test card?

I don't know if can help but "PayPal Payments - similar to Express Checkout in Classic APIs" method works just fine.

Thank you!

**Comment by stryd3r** [comment]
I succeeded also with "Payments using credit card information" method.

I just set the right proxy in sdk_config_propertoes
http.ProxyPort=3128
http.ProxyHost=proxymil.internal.*****.eu
http.UseProxy=true
http.ProxyUserName=c303036
http.ProxyPassword=*********

Thank you!
